package graphql

import (
	"context"
	"crypto/tls"
	"fmt"
	"log"
	"net"
	"strings"
	"sync"

	gql "github.com/99designs/gqlgen/graphql"
	"github.com/99designs/gqlgen/graphql/handler"
	"github.com/99designs/gqlgen/graphql/handler/extension"
	"github.com/99designs/gqlgen/graphql/playground"
	"github.com/goichi-dev/goichi/core"
	"github.com/goichi-dev/goichi/middleware"
	"github.com/valyala/fasthttp"
	"github.com/valyala/fasthttp/fasthttpadaptor"
)

type GraphQLServer struct {
	config    GraphQLConfig
	isRunning bool
	mu        sync.RWMutex
	server    *fasthttp.Server

	outerMW func(next fasthttp.RequestHandler) fasthttp.RequestHandler

	// Schema is the executable schema generated by gqlgen
	Schema gql.ExecutableSchema

	authSecret string
	authLookup string
}

func (gs *GraphQLServer) SetAuthSecret(secret string) {
	gs.mu.Lock()
	defer gs.mu.Unlock()
	gs.authSecret = secret
}

func (gs *GraphQLServer) SetAuthLookup(lookup string) {
	gs.mu.Lock()
	defer gs.mu.Unlock()
	gs.authLookup = lookup
}

func (gs *GraphQLServer) SetListener(ln net.Listener) {
	// Not used directly as fasthttp handles it in Start
}

func NewGraphQLServer(config GraphQLConfig) *GraphQLServer {
	config.SetDefaults()
	return &GraphQLServer{
		config: config,
	}
}

func (gs *GraphQLServer) GetInfo() string {
	return fmt.Sprintf("Query: %s, Playground: %s (Port %d)", gs.config.QueryPath, gs.config.PlaygroundPath, gs.config.Port)
}

func (gs *GraphQLServer) GetName() string {
	return "graphql"
}

func (gs *GraphQLServer) GetPaths() []string {
	return []string{gs.config.QueryPath, gs.config.PlaygroundPath}
}

// SetFastHTTPOuterMiddleware wraps the GraphQL HTTP handler with App-level protocol middleware.
func (gs *GraphQLServer) SetFastHTTPOuterMiddleware(wrap func(next fasthttp.RequestHandler) fasthttp.RequestHandler) {
	gs.mu.Lock()
	defer gs.mu.Unlock()
	gs.outerMW = wrap
}

// buildGQLHandler constructs the query handler with complexity limiting,
// introspection gating and unified-auth enforcement applied.
func (gs *GraphQLServer) buildGQLHandler() fasthttp.RequestHandler {
	schema := gs.Schema
	var base fasthttp.RequestHandler
	if schema == nil {
		base = func(ctx *fasthttp.RequestCtx) {
			ctx.SetContentType("application/json")
			ctx.SetBodyString(`{"data":{"ping":"pong"}}`)
		}
	} else {
		srv := handler.NewDefaultServer(schema)
		if gs.config.MaxComplexity > 0 {
			srv.Use(extension.FixedComplexityLimit(gs.config.MaxComplexity))
		}
		if !gs.config.EnableIntrospection {
			srv.AroundOperations(func(ctx context.Context, next gql.OperationHandler) gql.ResponseHandler {
				gql.GetOperationContext(ctx).DisableIntrospection = true
				return next(ctx)
			})
		}
		base = fasthttpadaptor.NewFastHTTPHandler(srv)
	}
	return gs.withAuth(base)
}

// withAuth wraps a handler so it rejects requests lacking a valid JWT when a
// unified auth secret (or RequireAuth) is configured.
func (gs *GraphQLServer) withAuth(next fasthttp.RequestHandler) fasthttp.RequestHandler {
	return func(ctx *fasthttp.RequestCtx) {
		gs.mu.RLock()
		secret := gs.authSecret
		lookup := gs.authLookup
		required := gs.config.RequireAuth
		gs.mu.RUnlock()

		if secret == "" && !required {
			next(ctx)
			return
		}
		if secret == "" {
			ctx.SetStatusCode(fasthttp.StatusInternalServerError)
			ctx.SetContentType("application/json")
			ctx.SetBodyString(`{"errors":[{"message":"auth not configured"}]}`)
			return
		}
		raw := middleware.ExtractToken(&core.Context{RequestCtx: ctx}, lookup)
		if _, errMsg := middleware.ValidateJWT(raw, secret); errMsg != "" {
			ctx.SetStatusCode(fasthttp.StatusUnauthorized)
			ctx.SetContentType("application/json")
			ctx.SetBodyString(`{"errors":[{"message":"unauthorized"}]}`)
			return
		}
		next(ctx)
	}
}

func (gs *GraphQLServer) Handler() func(c *fasthttp.RequestCtx) {
	gqlHandler := gs.buildGQLHandler()

	var playHandler fasthttp.RequestHandler
	if gs.config.EnablePlayground {
		playHandler = fasthttpadaptor.NewFastHTTPHandler(playground.Handler("GraphQL playground", gs.config.QueryPath))
	}

	h := func(ctx *fasthttp.RequestCtx) {
		path := string(ctx.Path())
		switch {
		case path == gs.config.QueryPath:
			gqlHandler(ctx)
		case path == gs.config.PlaygroundPath:
			if playHandler != nil {
				playHandler(ctx)
			} else {
				ctx.Error("Not Found", fasthttp.StatusNotFound)
			}
		case strings.HasSuffix(path, "/query") || strings.HasSuffix(path, "/graphql"):
			gqlHandler(ctx)
		default:
			ctx.Error("Not Found", fasthttp.StatusNotFound)
		}
	}

	gs.mu.RLock()
	outer := gs.outerMW
	gs.mu.RUnlock()
	if outer != nil {
		return outer(h)
	}
	return h
}

func (gs *GraphQLServer) Start(ctx context.Context) error {
	gs.mu.Lock()
	if gs.isRunning {
		gs.mu.Unlock()
		return nil
	}
	gs.mu.Unlock()

	if !gs.config.Enabled {
		log.Printf("[GraphQL] Disabled, skipping start")
		return nil
	}

	if gs.Schema == nil {
		log.Printf("[GraphQL] No schema provided, using simple responder")
	}
	gqlHandler := gs.buildGQLHandler()

	var playHandler fasthttp.RequestHandler
	if gs.config.EnablePlayground {
		playHandler = fasthttpadaptor.NewFastHTTPHandler(playground.Handler("GraphQL playground", gs.config.QueryPath))
	}

	router := func(ctx *fasthttp.RequestCtx) {
		switch string(ctx.Path()) {
		case gs.config.QueryPath:
			gqlHandler(ctx)
		case gs.config.PlaygroundPath:
			if playHandler != nil {
				playHandler(ctx)
			} else {
				ctx.Error("Not Found", fasthttp.StatusNotFound)
			}
		default:
			ctx.Error("Not Found", fasthttp.StatusNotFound)
		}
	}

	handler := fasthttp.RequestHandler(router)
	gs.mu.RLock()
	outer := gs.outerMW
	gs.mu.RUnlock()
	if outer != nil {
		handler = outer(handler)
	}

	gs.server = &fasthttp.Server{
		Handler: handler,
	}

	addr := fmt.Sprintf("%s:%d", gs.config.Address, gs.config.Port)
	ln, err := net.Listen("tcp", addr)
	if err != nil {
		return err
	}

	if gs.config.TLSEnabled() {
		cert, err := tls.LoadX509KeyPair(gs.config.TLSCertFile, gs.config.TLSKeyFile)
		if err != nil {
			return fmt.Errorf("graphql tls: %w", err)
		}
		ln = tls.NewListener(ln, &tls.Config{
			Certificates: []tls.Certificate{cert},
			MinVersion:   tls.VersionTLS12,
		})
	}

	gs.mu.Lock()
	gs.isRunning = true
	gs.mu.Unlock()

	go func() {
		if err := gs.server.Serve(ln); err != nil {
			log.Printf("[GraphQL] Server error: %v", err)
		}
	}()

	log.Printf("[GraphQL] Server started on %s (query path: %s, playground: %s)",
		addr, gs.config.QueryPath, gs.config.PlaygroundPath)
	return nil
}

func (gs *GraphQLServer) Stop(ctx context.Context) error {
	gs.mu.Lock()
	defer gs.mu.Unlock()

	if !gs.isRunning {
		return nil
	}

	if gs.server != nil {
		gs.server.Shutdown()
	}

	gs.isRunning = false
	log.Printf("[GraphQL] Server stopped")
	return nil
}

func (gs *GraphQLServer) IsRunning() bool {
	gs.mu.RLock()
	defer gs.mu.RUnlock()
	return gs.isRunning
}
